#!/bin/sh
DIR=${HOME}/.local/bin
STATUS="statusbar.sh"
if [ -f "${DIR}/${STATUS}" ]; then
	/bin/sh "${DIR}/${STATUS}" &
else
	while true; do
		xsetroot -name "$(date)"
		sleep 1
	done &
fi
exec /usr/bin/raven
